name: Scheduled run

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 1,3,5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code from remote repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Newman & Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman
        run: 'newman run Trello_Anna.postman_collection.json -e Trello_Environment.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export report.html'

      - name: Output the results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: "*.html"

      - name: Send report by email
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL.USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Actions job result
          to: anilser19@gmail.ru
          from: GitHub Trello_Postman-testing Repo
          attachments: report.html
          
          
