# This is a basic workflow to help you get started with Actions

name: Scheduled run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 1,3,5'

      # 1.Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: pull code from remote repository
        uses: actions/checkout@v4

      # 2.Install Node.js
      - name: setup Node.js
        uses: actions/setup-node@v4

      # 3.Install Newman & Reporter
      - name: Install Newman & Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
 
      - name: Run Postman
        run: 'newman run Trello_Anna.postman_collection.json -e Trello_Environment.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export report.html'

       # 5. Upload artifact
      - name: Output the results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: "*html"

       # 6. Send mail
       - name: Send mail
         uses: dawidd6/action-send-mail@v4
         with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: anilser19@gmail.com
          password: fibf xneh ersk qzzn
          subject: Github Actions job result
          to: anilser19@gmail.ru
          from:  GitHub Trello_Postman-testing Repo
       
          
          